package com.myapplications.mypasswords.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Blue Colors
val BluePrimaryLight = Color(0xFF0061A4)
val OnBluePrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD1E4FF)
val OnBluePrimaryContainerLight = Color(0xFF001D36)
val BlueSecondaryLight = Color(0xFF535F70)
val OnBlueSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFD7E3F7)
val OnBlueSecondaryContainerLight = Color(0xFF101C2B)
val BlueTertiaryLight = Color(0xFF6B5778)
val OnBlueTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFF2DAFF)
val OnBlueTertiaryContainerLight = Color(0xFF251431)
val BlueErrorLight = Color(0xFFBA1A1A)
val OnBlueErrorLight = Color(0xFFFFFFFF)
val BlueErrorContainerLight = Color(0xFFFFDAD6)
val OnBlueErrorContainerLight = Color(0xFF410002)
val BlueBackgroundLight = Color(0xFFFDFBFF)
val OnBlueBackgroundLight = Color(0xFF1A1C1E)
val BlueSurfaceLight = Color(0xFFFDFBFF)
val OnBlueSurfaceLight = Color(0xFF1A1C1E)
val BlueSurfaceVariantLight = Color(0xFFDFE2EB)
val OnBlueSurfaceVariantLight = Color(0xFF43474E)
val BlueOutlineLight = Color(0xFF73777F)

// Dark Theme Blue Colors
val BluePrimaryDark = Color(0xFF9ECAFF)
val OnBluePrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val OnBluePrimaryContainerDark = Color(0xFFD1E4FF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val OnBlueSecondaryDark = Color(0xFF253140)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val OnBlueSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD6BEE4)
val OnBlueTertiaryDark = Color(0xFF3B2948)
val BlueTertiaryContainerDark = Color(0xFF523F5F)
val OnBlueTertiaryContainerDark = Color(0xFFF2DAFF)
val BlueErrorDark = Color(0xFFFFB4AB)
val OnBlueErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val OnBlueErrorContainerDark = Color(0xFFFFDAD6)
val BlueBackgroundDark = Color(0xFF1A1C1E)
val OnBlueBackgroundDark = Color(0xFFE2E2E6)
val BlueSurfaceDark = Color(0xFF1A1C1E)
val OnBlueSurfaceDark = Color(0xFFE2E2E6)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val OnBlueSurfaceVariantDark = Color(0xFFC3C7CF)
val BlueOutlineDark = Color(0xFF8D9199)